// <auto-generated />
namespace DoAn_LapTrinhWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class model1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110091115005_model1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
